import React, { useState } from "react";
import { Building2, Edit, Eye, Filter, MapPin, Plus, Search, Trash2, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useData } from "../../../context/DataContext";

export const FranchiseList = () => {
  const navigate = useNavigate();
  const { franchises, deleteFranchise } = useData();
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("All");
  const [error, setError] = useState("");
  const filtered = franchises.filter((franchise) => {
    const query = search.toLowerCase();
    const matchesSearch = [franchise.name, franchise.owner, franchise.location, franchise.code, franchise.email].some((value) => String(value || "").toLowerCase().includes(query));
    return matchesSearch && (status === "All" || franchise.status === status);
  });
  const remove = async (franchise) => {
    if (!window.confirm(`Deactivate ${franchise.name}?`)) return;
    try { setError(""); await deleteFranchise(franchise.id); } catch (deleteError) { setError(deleteError.message); }
  };
  return <div className="space-y-6 pb-12">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">Franchise Network</h1><p className="mt-1 text-xs text-slate-600">Manage authorized learning franchise centers.</p></div><button onClick={() => navigate('/admin/franchises/add')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-amber-600 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-orange-500/20"><Plus className="h-4 w-4" /> Add New Franchise</button></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-600">{error}</div>}
    <div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row md:items-center md:justify-between"><label className="relative w-full md:w-80"><Search className="absolute left-3.5 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search franchise, owner, city..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2 pl-10 pr-4 text-xs outline-none focus:border-orange-500" /></label><label className="flex items-center gap-2 text-xs font-medium text-slate-600"><Filter className="h-4 w-4 text-slate-400" /> Status <select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-800"><option>All</option><option>Active</option><option>Pending</option><option>Suspended</option><option>Inactive</option></select></label></div>
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-100 bg-slate-50 text-[10px] font-semibold uppercase text-slate-600"><tr><th className="px-4 py-4">Code</th><th className="px-4 py-4">Franchise</th><th className="px-4 py-4">Owner</th><th className="px-4 py-4">Location</th><th className="px-4 py-4">Students</th><th className="px-4 py-4">Status</th><th className="px-4 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.length === 0 ? <tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">No franchises found.</td></tr> : filtered.map((franchise) => <tr key={franchise.id} className="hover:bg-slate-50"><td className="px-4 py-4 font-mono font-bold text-orange-600">{franchise.code || '-'}</td><td className="px-4 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-100 text-orange-700"><Building2 className="h-4 w-4" /></span><div><p className="font-bold text-slate-900">{franchise.name}</p><p className="text-[10px] text-slate-500">{franchise.email}</p></div></div></td><td className="px-4 py-4 font-semibold text-slate-800">{franchise.owner}</td><td className="px-4 py-4"><span className="flex items-center gap-1 text-slate-700"><MapPin className="h-3.5 w-3.5 text-slate-400" />{franchise.location || '-'}</span></td><td className="px-4 py-4"><span className="flex items-center gap-1 font-bold text-slate-900"><Users className="h-3.5 w-3.5 text-blue-500" />{franchise.studentsCount}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${franchise.status === 'Active' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{franchise.status}</span></td><td className="px-4 py-4"><div className="flex justify-end gap-2"><button onClick={() => navigate(`/admin/franchises/${franchise.id}`)} className="inline-flex items-center gap-1 rounded-lg bg-orange-50 px-2 py-1.5 font-bold text-orange-600"><Eye className="h-3.5 w-3.5" />View</button><button onClick={() => navigate(`/admin/franchises/${franchise.id}/edit`)} className="inline-flex items-center gap-1 rounded-lg bg-slate-100 px-2 py-1.5 font-bold text-slate-700"><Edit className="h-3.5 w-3.5" />Edit</button><button onClick={() => remove(franchise)} className="inline-flex items-center gap-1 rounded-lg bg-red-50 px-2 py-1.5 font-bold text-red-600"><Trash2 className="h-3.5 w-3.5" />Delete</button></div></td></tr>)}</tbody></table></div></div>
  </div>;
};
