import React, { useEffect, useState } from "react";
import { ArrowLeft, Building2, Edit, Loader2, Mail, MapPin, Phone, User } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { normalizeCoaching, useData } from "../../../context/DataContext";
import { apiFetch } from "../../../utils/api";

export const FranchiseDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { franchises, students } = useData();
  const [franchise, setFranchise] = useState(() => franchises.find((item) => item.id === id) || null);
  const [loading, setLoading] = useState(!franchise);
  const [error, setError] = useState("");
  useEffect(() => { const load = async () => { try { setLoading(true); const response = await apiFetch(`/api/coaching/${id}`); setFranchise(normalizeCoaching(response.coaching)); } catch (loadError) { setError(loadError.message); } finally { setLoading(false); } }; load(); }, [id]);
  if (loading) return <div className="flex min-h-[400px] items-center justify-center gap-2 text-sm text-slate-500"><Loader2 className="h-5 w-5 animate-spin" /> Loading franchise...</div>;
  if (error || !franchise) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">{error || 'Franchise not found.'}</div>;
  const franchiseStudents = students.filter((student) => student.coachingId === id || student.franchiseId === id || student.franchise === franchise.name);
  const fields = [['Center Code', franchise.code || '-'], ['Franchise ID', franchise.id], ['Owner', franchise.owner], ['Email', franchise.email], ['Phone', franchise.phone], ['City', franchise.location || '-'], ['Address', franchise.address || '-'], ['Joined', franchise.established || '-']];
  return <div className="mx-auto max-w-5xl space-y-6 pb-12"><Link to="/admin/franchises" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-orange-500"><ArrowLeft className="h-4 w-4" /> Back to Franchises</Link><div className="flex flex-col justify-between gap-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:flex-row md:items-center"><div className="flex items-start gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-orange-500 to-amber-500 text-white"><Building2 className="h-8 w-8" /></span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold text-slate-900">{franchise.name}</h1><span className="rounded-full bg-orange-100 px-2.5 py-1 text-xs font-bold text-orange-800">{franchise.code || 'No code'}</span><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-700">{franchise.status}</span></div><p className="mt-2 flex items-center gap-1 text-sm text-slate-600"><MapPin className="h-4 w-4" /> {franchise.address || franchise.location || 'Address not added'}</p></div></div><button onClick={() => navigate(`/admin/franchises/${id}/edit`)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-orange-600"><Edit className="h-4 w-4" /> Edit Franchise</button></div><div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 font-bold text-slate-900">Franchise Details</h2><div className="grid gap-5 sm:grid-cols-2">{fields.map(([label, value]) => <div key={label}><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-bold text-slate-900">{value}</p></div>)}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 font-bold text-slate-900">Quick Summary</h2><div className="space-y-4 text-sm"><p className="flex items-center gap-2 text-slate-700"><User className="h-4 w-4 text-orange-500" /> {franchise.owner}</p><p className="flex items-center gap-2 text-slate-700"><Mail className="h-4 w-4 text-orange-500" /> {franchise.email}</p><p className="flex items-center gap-2 text-slate-700"><Phone className="h-4 w-4 text-orange-500" /> {franchise.phone}</p><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">Enrolled Students</p><p className="mt-1 text-2xl font-extrabold text-slate-900">{franchiseStudents.length}</p></div></div></section></div></div>;
};
