// Compatibility facade: legacy UI reads Redux server state through this context.
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAppDispatch, useAppSelector } from "../hooks/redux";
import { fetchCourses, createCourse } from "../store/courses/courseThunks";
import { setItems as setCourseItems } from "../store/courses/courseSlice";
import { fetchStudents, createStudent } from "../store/students/studentThunks";
import { fetchFranchises, createFranchise as createFranchiseThunk, updateFranchise as updateFranchiseThunk, deleteFranchise as deleteFranchiseThunk } from "../store/franchises/franchiseThunks";
import { fetchFees } from "../store/fees/feeThunks";
const DataContext = createContext(null);
export const normalizeCoaching = (item) => ({ ...item, id: item._id || item.id, owner: item.ownerName || "", location: [item.city, item.state].filter(Boolean).join(", "), status: item.status ? item.status[0].toUpperCase() + item.status.slice(1) : "Pending" });
const normalizeStudent = (item) => ({ ...item, id: item.studentId || item._id, course: item.courseId?.title || item.course || "", franchise: item.coachingId?.name || item.franchise || "", feesTotal: `₹${Number(item.registrationFee || 0) + Number(item.courseFee || 0) + Number(item.certificateFee || 0)}`, feesPaid: `₹${Number(item.totalPaid || 0)}`, feesPending: `₹${Number(item.totalPending || 0)}`, attendance: `${item.attendancePercentage ?? 0}%` });
export const DataProvider = ({ children }) => {
  const dispatch = useAppDispatch(); const courses = useAppSelector((s) => s.courses.items); const students = useAppSelector((s) => s.students.items); const franchises = useAppSelector((s) => s.franchises.items); const fees = useAppSelector((s) => s.fees.items); const payments = useAppSelector((s) => s.fees.payments); const [toasts, setToasts] = useState([]); const [notifications, setNotifications] = useState([]);
  useEffect(() => { if (localStorage.getItem("ai_scholars_token")) { dispatch(fetchCourses()); dispatch(fetchStudents({ limit: 1000 })); dispatch(fetchFees()); dispatch(fetchFranchises()); } }, [dispatch]);
  const showToast = (message, type = "success") => { const id = Date.now(); setToasts((v) => [...v, { id, message, type }]); setTimeout(() => setToasts((v) => v.filter((t) => t.id !== id)), 4000); };
  const run = async (action, message) => { const result = await dispatch(action).unwrap(); if (message) showToast(message); return result; };
  const value = useMemo(() => ({ franchises: franchises.map(normalizeCoaching), courses, students: students.map(normalizeStudent), fees, payments, certificates: [], notifications, admins: [], enrollmentChartData: [], toasts, showToast, removeToast: (id) => setToasts((v) => v.filter((t) => t.id !== id)), loadSharedData: () => Promise.all([dispatch(fetchCourses()), dispatch(fetchStudents({ limit: 1000 })), dispatch(fetchFees()), dispatch(fetchFranchises())]), createFranchise: (payload) => run(createFranchiseThunk(payload), `Franchise "${payload.name}" created successfully!`), updateFranchise: (id, payload) => run(updateFranchiseThunk({ id, payload }), "Franchise updated successfully!"), deleteFranchise: (id) => run(deleteFranchiseThunk(id), "Franchise deleted successfully!"), addCourse: (payload) => run(createCourse(payload), `Course "${payload.title}" created successfully!`), replaceCourses: (items) => dispatch(setCourseItems(items)), addStudent: (payload) => run(createStudent(payload), `Student "${payload.name}" enrolled successfully!`), addAdmin: (admin) => showToast(`Admin "${admin.name}" added successfully!`), issueCertificate: () => showToast("Certificate issuance is handled by the server eligibility flow."), markNotificationRead: (id) => setNotifications((v) => v.map((n) => n.id === id ? { ...n, read: true } : n)), markAllNotificationsRead: () => setNotifications((v) => v.map((n) => ({ ...n, read: true }))), createNotification: async (payload) => { const item = { ...payload, id: Date.now() }; setNotifications((v) => [item, ...v]); return item; }, updateNotification: async (id, payload) => setNotifications((v) => v.map((n) => n.id === id ? { ...n, ...payload } : n)), deleteNotification: async (id) => setNotifications((v) => v.filter((n) => n.id !== id)) }), [courses, students, franchises, fees, payments, notifications, toasts, dispatch]);
  return <DataContext.Provider value={value}>{children}</DataContext.Provider>;
};
export const useData = () => { const value = useContext(DataContext); if (!value) throw new Error("useData must be used inside DataProvider"); return value; };
