import { useEffect, useMemo, useState } from "react";
import { Eye, Loader2, Search, Users } from "lucide-react";
import { apiFetch } from "../../../utils/api";

const TeacherStudents = () => { const [students, setStudents] = useState([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState(null); const [error, setError] = useState("");
  useEffect(() => { apiFetch("/api/portal/students").then((r) => setStudents(r.data || [])).catch((e) => setError(e.message)); }, []);
  const filtered = useMemo(() => students.filter((s) => `${s.name} ${s.email} ${s.courseId?.title} ${s.batchId?.name}`.toLowerCase().includes(query.toLowerCase())), [students, query]);
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Learner directory</p><h1 className="mt-2 text-3xl font-black text-slate-900">My Students</h1><p className="mt-2 text-sm text-slate-500">Students from your assigned courses and batches only.</p></div>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<label className="relative block"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search student, course or batch" className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-blue-500" /></label><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Student</th><th className="p-4">Course</th><th className="p-4">Batch</th><th className="p-4">Attendance</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((s) => <tr key={s._id} className="hover:bg-slate-50"><td className="p-4"><p className="font-bold text-slate-900">{s.name}</p><p className="text-xs text-slate-500">{s.email || s.studentId || ""}</p></td><td className="p-4">{s.courseId?.title || "-"}</td><td className="p-4">{s.batchId?.name || "-"}</td><td className="p-4">{s.attendancePercentage || 0}%</td><td className="p-4"><button onClick={() => setSelected(s)} className="inline-flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700"><Eye size={14} /> View</button></td></tr>)}{!filtered.length && <tr><td colSpan="5" className="p-10 text-center text-slate-500"><Users className="mx-auto mb-2 text-slate-300" />No students found.</td></tr>}</tbody></table></div></div>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" onClick={() => setSelected(null)}><div onClick={(e) => e.stopPropagation()} className="w-full max-w-md rounded-2xl bg-white p-6"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">{selected.name}</h2><p className="text-sm text-slate-500">{selected.email || "Student profile"}</p></div><button onClick={() => setSelected(null)} className="text-slate-400">×</button></div><div className="mt-5 grid gap-3 text-sm"><p><b>Course:</b> {selected.courseId?.title || "-"}</p><p><b>Batch:</b> {selected.batchId?.name || "-"}</p><p><b>Status:</b> {selected.status || "active"}</p><p><b>Attendance:</b> {selected.attendancePercentage || 0}%</p></div></div></div>}</div>;
}; export default TeacherStudents;
