import React, { useState } from "react";
import { Loader2, Printer, X } from "lucide-react";
import { assetUrl } from "../../../utils/api";
import logo from "../../../../assist/logo.png";
import "./StudentIdCard.css";

const formatDate = (value) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value)) : "—";
const value = (item) => item || "—";
const Details = ({ label, children }) => <div className="id-detail"><span>{label}</span><strong>{value(children)}</strong></div>;

export default function StudentIdCardModal({ student, loading, error, onClose }) {
  const [side, setSide] = useState("front");
  const print = () => window.print();
  return <div className="id-modal fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/65 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Student ID card preview"><div className="id-modal-panel w-full max-w-4xl rounded-3xl bg-white shadow-2xl"><div className="id-controls flex items-center justify-between border-b border-slate-200 px-5 py-4 sm:px-7"><div><h2 className="font-black text-slate-900">Student ID Card</h2><p className="text-xs text-slate-500">Preview both sides before printing.</p></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label="Close preview"><X /></button></div>{loading ? <div className="flex h-80 items-center justify-center gap-2 text-sm font-bold text-slate-500"><Loader2 className="animate-spin"/> Loading latest student data...</div> : error ? <div className="p-8 text-center text-sm font-semibold text-red-600">{error}</div> : student && <><div className="id-controls flex justify-center gap-2 px-5 pt-5"><button onClick={() => setSide("front")} className={`rounded-lg px-4 py-2 text-xs font-black ${side === "front" ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>FRONT</button><button onClick={() => setSide("back")} className={`rounded-lg px-4 py-2 text-xs font-black ${side === "back" ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>BACK</button></div><div className="id-card-stage p-5 sm:p-8"><div className={`student-id-card ${side === "back" ? "is-back" : ""}`}>
    <div className="id-brand"><img src={logo} alt="AI Scholars"/><div className="id-brand-lines"/></div>
    {side === "front" ? <div className="id-front"><div className="id-info"><h3>{value(student.name)}</h3><div className="id-detail-grid"><Details label="ID No.">{student.studentId}</Details><Details label="Joined">{formatDate(student.joiningDate)}</Details><Details label="DOB">{formatDate(student.dob)}</Details><Details label="Mobile">{student.mobile}</Details></div></div><div className="id-photo">{student.photo ? <img src={assetUrl(student.photo)} alt={student.name} onError={(e) => { e.currentTarget.style.display = "none"; }}/>: <span>PHOTO</span>}</div></div> : <div className="id-back"><div className="id-back-details"><Details label="Course">{student.courseId?.title || student.courseId?.name}</Details><Details label="Gender">{student.gender}</Details><Details label="Blood Group">{student.bloodGroup}</Details><Details label="Father's Name">{student.fatherName}</Details><Details label="Address">{student.address}</Details></div><div className="id-signature"><span>For AI SCHOLARS</span><div className="id-sign">Authorized</div><b>Auth. Signature</b></div></div>}
    <div className="id-footer">Address - shop 5-6, 2nd floor, S-22, Shoe Market, Sanjay Place, Agra - 282002</div>
  </div></div><div className="id-controls flex justify-end gap-3 border-t border-slate-200 px-5 py-4 sm:px-7"><button onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Close</button><button onClick={print} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white"><Printer size={16}/> Print ID Card</button></div></>}</div></div>;
}
